# ===================================================================
# 1. НАСТРОЙКИ БАЗЫ ДАННЫХ POSTGRESQL
# ===================================================================
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.url=jdbc:postgresql://localhost:5432/user_service_db
spring.datasource.username=postgres
spring.datasource.password=root

# ===================================================================
# 2. НАСТРОЙКИ JPA / HIBERNATE
# ===================================================================
spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# ===================================================================
# 3. НАСТРОЙКИ APACHE KAFKA (ОБЩИЕ И PRODUCER)
# ===================================================================
# Адрес брокера Kafka (по умолчанию локальный)
spring.kafka.bootstrap-servers=localhost:9092

# Сериализатор для ключей сообщений (используем обычные строки)
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer

# Сериализатор для значений (автоматически превращает наши Java-рекорды/DTO в JSON)
spring.kafka.producer.value-serializer=org.springframework.kafka.support.serializer.JsonSerializer

# ===================================================================
# 4. НАСТРОЙКИ APACHE KAFKA (CONSUMER)
# ===================================================================
# Идентификатор группы потребителей по умолчанию
spring.kafka.consumer.group-id=notification-group

# С какого момента читать топик, если группа новая (earliest — с самого начала)
spring.kafka.consumer.auto-offset-reset=earliest

# Десериализаторы для чтения сообщений
spring.kafka.consumer.key-deserializer=org.apache.kafka.common.serialization.StringDeserializer

# Безопасная десериализация: если прилетит битый JSON, ErrorHandlingDeserializer предотвратит падение контейнера
spring.kafka.consumer.value-deserializer=org.springframework.kafka.support.serializer.ErrorHandlingDeserializer
spring.kafka.properties.spring.deserializer.value.delegate.class=org.springframework.kafka.support.serializer.JsonDeserializer

# Говорим Spring доверять пакету с нашими DTO классами при чтении JSON из Кафки
spring.kafka.properties.spring.json.trusted.packages=io.github.ArtemV2007.dto

# ===================================================================
# 5. НАСТРОЙКИ ПОЧТОВОГО СЕРВЕРА (SMTP)
# ===================================================================
# Для локальной разработки и тестов обычно используют порты заглушек (например, Mailhog на 1025)
spring.mail.host=localhost
spring.mail.port=1025
spring.mail.username=test
spring.mail.password=test

# Дополнительные свойства SMTP протокола
spring.mail.properties.mail.smtp.auth=false
spring.mail.properties.mail.smtp.starttls.enable=false
